# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 588)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 571, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Debit = QtWidgets.QComboBox(self.tab)
        self.Debit.setGeometry(QtCore.QRect(150, 80, 131, 22))
        self.Debit.setEditable(True)
        self.Debit.setObjectName("Debit")
        self.Debit.addItem(None)
        self.Debit.addItem("Cash")
        self.Debit.addItem("Accounts Receivable")
        self.Debit.addItem("Notes Receivable")
        self.Debit.addItem("Supplies")
        self.Debit.addItem("Equipment")
        self.Debit.addItem("Accounts Payable")
        self.Debit.addItem("Notes Payable")
        self.Debit.addItem("Unearned Revenue")
        self.Debit.addItem("Service Revenue")
        self.Debit.addItem("Capital")
        self.Debit.addItem("Drawings")
        self.Debit.addItem("Rent Expense")
        self.Debit.addItem("Salaries Expense")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(40, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_3.setObjectName("label_3")
        self.Value = QtWidgets.QLineEdit(self.tab)
        self.Value.setGeometry(QtCore.QRect(150, 180, 131, 20))
        self.Value.setObjectName("Value")
        self.Credit = QtWidgets.QComboBox(self.tab)
        self.Credit.setGeometry(QtCore.QRect(150, 130, 131, 22))
        self.Credit.setEditable(True)
        self.Credit.setObjectName("Credit")
        self.Credit.addItem(None)
        self.Credit.addItem("Cash")
        self.Credit.addItem("Accounts Receivable")
        self.Credit.addItem("Notes Receivable")
        self.Credit.addItem("Supplies")
        self.Credit.addItem("Equipment")
        self.Credit.addItem("Accounts Payable")
        self.Credit.addItem("Notes Payable")
        self.Credit.addItem("Unearned Revenue")
        self.Credit.addItem("Service Revenue")
        self.Credit.addItem("Capital")
        self.Credit.addItem("Drawings")
        self.Credit.addItem("Rent Expense")
        self.Credit.addItem("Salaries Expense")
        self.Submit = QtWidgets.QPushButton(self.tab)
        self.Submit.setGeometry(QtCore.QRect(260, 220, 75, 23))
        self.Submit.setObjectName("Submit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 571, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(-5, -9, 571, 511))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(-10, -10, 581, 511))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(10)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.ShowTrial = QtWidgets.QPushButton(Dialog)
        self.ShowTrial.setGeometry(QtCore.QRect(500, 550, 75, 23))
        self.ShowTrial.setObjectName("ShowTrial")
        self.ShowJournal = QtWidgets.QPushButton(Dialog)
        self.ShowJournal.setGeometry(QtCore.QRect(400, 550, 75, 23))
        self.ShowJournal.setObjectName("ShowJournal")
        self.ShowLedger = QtWidgets.QPushButton(Dialog)
        self.ShowLedger.setGeometry(QtCore.QRect(300, 550, 75, 23))
        self.ShowLedger.setObjectName("ShowLedger")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Debit.setItemText(0,_translate("Dialog",""))
        self.Debit.setItemText(1, _translate("Dialog", "Cash"))
        self.Debit.setItemText(2, _translate("Dialog", "Accounts Receivable"))
        self.Debit.setItemText(3, _translate("Dialog", "Notes Receivable"))
        self.Debit.setItemText(4, _translate("Dialog", "Supplies"))
        self.Debit.setItemText(5, _translate("Dialog", "Equipment"))
        self.Debit.setItemText(6, _translate("Dialog", "Accounts Payable"))
        self.Debit.setItemText(7, _translate("Dialog", "Notes Payable"))
        self.Debit.setItemText(8, _translate("Dialog", "Unearned Revenue"))
        self.Debit.setItemText(9, _translate("Dialog", "Service Revenue"))
        self.Debit.setItemText(10, _translate("Dialog", "Capital"))
        self.Debit.setItemText(11, _translate("Dialog", "Drawings"))
        self.Debit.setItemText(12, _translate("Dialog", "Rent Expense"))
        self.Debit.setItemText(13, _translate("Dialog", "Salaries Expense"))
        self.label.setText(_translate("Dialog", "Debit"))
        self.label_2.setText(_translate("Dialog", "Credit"))
        self.label_3.setText(_translate("Dialog", "Value"))
        self.Credit.setItemText(0,_translate("Dialog",""))
        self.Credit.setItemText(1, _translate("Dialog", "Cash"))
        self.Credit.setItemText(2, _translate("Dialog", "Accounts Receivable"))
        self.Credit.setItemText(3, _translate("Dialog", "Notes Receivable"))
        self.Credit.setItemText(4, _translate("Dialog", "Supplies"))
        self.Credit.setItemText(5, _translate("Dialog", "Equipment"))
        self.Credit.setItemText(6, _translate("Dialog", "Accounts Payable"))
        self.Credit.setItemText(7, _translate("Dialog", "Notes Payable"))
        self.Credit.setItemText(8, _translate("Dialog", "Unearned Revenue"))
        self.Credit.setItemText(9, _translate("Dialog", "Service Revenue"))
        self.Credit.setItemText(10, _translate("Dialog", "Capital"))
        self.Credit.setItemText(11, _translate("Dialog", "Drawings"))
        self.Credit.setItemText(12, _translate("Dialog", "Rent Expense"))
        self.Credit.setItemText(13, _translate("Dialog", "Salaries Expense"))
        self.Submit.setText(_translate("Dialog", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Input"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Trial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Journal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Ledger"))
        self.ShowTrial.setText(_translate("Dialog", "Trial"))
        self.ShowJournal.setText(_translate("Dialog", "Journal"))
        self.ShowLedger.setText(_translate("Dialog", "Ledger"))
if __name__ == "__main__":
    print("0")
    msg = QtWidgets.QMessageBox()
    print("1")
    msg.setIcon(QtWidgets.QMessageBox.Critical)
    msg.setText("Error")
    msg.setInformativeText('More information')
    msg.setWindowTitle("Error")
    msg.exec_()
